version: '2.1'

services:

  master:
    hostname: master
    build:
      context: .
      dockerfile: Dockerfile-master
    ports:
      - "15432:5432"
    networks:
      - postgres10

  standby:
    hostname: standby
    build:
      context: .
      dockerfile: Dockerfile-standby
    ports:
      - "25432:5432"
    networks:
      - postgres10

  master2:
    hostname: master2
    build:
      context: .
      dockerfile: Dockerfile-master2
    ports:
      - "15433:5432"
    networks:
      - postgres10

  standby2:
    hostname: standby2
    build:
      context: .
      dockerfile: Dockerfile-standby2
    ports:
      - "25433:5432"
    networks:
      - postgres10

networks:
  postgres10:
    driver: bridge
